import AuthContextProvider from "@/contexts/AuthContext";
import AuthProvider from "@/providers/AuthProvider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <AuthProvider>
          <AuthContextProvider>
            <div className="h-screen flex flex-col">
              <div className="flex flex-1 overflow-hidden">
                <div className="h-full"></div>
                <div className="bg-white w-full overflow-auto">{children}</div>
              </div>
            </div>
          </AuthContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
