import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import NavbarEmployer from "@/components/navbar/NavbarEmployer";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let type = "user"
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <div className="header">
            <Header />
          </div>
          <div className="flex flex-1 overflow-hidden">
            <div className="h-full">
              {type === "user" && <Navbar />}
              {type === "employer" && <NavbarEmployer />}
            </div>
            <div className="bg-white w-full overflow-auto">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
